export const GATEWAY_ABI = [
  {
    inputs: [
      { name: "proof", type: "bytes" },
      { name: "publicInstances", type: "uint256[]" },
      { name: "agentId", type: "uint256" },
      { name: "stationId", type: "uint256" },
    ],
    name: "submitVerifiedInference",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "publicInstances", type: "uint256[]" },
      { name: "agentId", type: "uint256" },
      { name: "stationId", type: "uint256" },
    ],
    name: "submitOffchainVerified",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "index", type: "uint256" }],
    name: "getRecord",
    outputs: [
      {
        components: [
          { name: "agentId", type: "uint256" },
          { name: "proofHash", type: "bytes32" },
          { name: "inputHash", type: "bytes32" },
          { name: "publicInstances", type: "uint256[]" },
          { name: "timestamp", type: "uint256" },
          { name: "verified", type: "bool" },
          { name: "decision", type: "uint8" },
          { name: "dataAuthentic", type: "bool" },
        ],
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "agentId", type: "uint256" }],
    name: "getAgentRecords",
    outputs: [{ type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAuthenticated",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "recordIndex", type: "uint256" },
      { name: "greenFieldURI", type: "string" },
      { name: "contentHash", type: "bytes32" },
    ],
    name: "anchorToGreenField",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "recordIndex", type: "uint256" }],
    name: "isAnchored",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "agentId", type: "uint256" }],
    name: "getAgentRecordCount",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "agentId", type: "uint256" }],
    name: "getAgentScore",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalVerifications",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalClaimsTriggered",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalRecords",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingAdmin",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "insurancePoolBalance",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultPayoutAmount",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "agentId", type: "uint256" },
      { indexed: false, name: "payoutAddress", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "ClaimPayoutTriggered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "agentId", type: "uint256" },
      { indexed: true, name: "recordIndex", type: "uint256" },
      { indexed: false, name: "proofHash", type: "bytes32" },
      { indexed: false, name: "verified", type: "bool" },
      { indexed: false, name: "decision", type: "uint8" },
      { indexed: false, name: "dataAuthentic", type: "bool" },
    ],
    name: "InferenceSubmitted",
    type: "event",
  },
] as const;

export const NFA_ABI = [
  {
    inputs: [
      {
        components: [
          { name: "name", type: "string" },
          { name: "persona", type: "string" },
          { name: "voiceHash", type: "bytes32" },
          { name: "animationURI", type: "string" },
          { name: "vaultURI", type: "string" },
          { name: "vaultHash", type: "bytes32" },
          { name: "avatarId", type: "uint8" },
        ],
        type: "tuple",
      },
    ],
    name: "mint",
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getProfile",
    outputs: [
      {
        components: [
          { name: "totalPredictions", type: "uint256" },
          { name: "correctPredictions", type: "uint256" },
          { name: "learningRoot", type: "bytes32" },
          { name: "reputationScore", type: "uint256" },
        ],
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getAgentMetadata",
    outputs: [
      {
        components: [
          { name: "name", type: "string" },
          { name: "persona", type: "string" },
          { name: "voiceHash", type: "bytes32" },
          { name: "animationURI", type: "string" },
          { name: "vaultURI", type: "string" },
          { name: "vaultHash", type: "bytes32" },
          { name: "avatarId", type: "uint8" },
        ],
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAgents",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const NFA_FULL_ABI = [
  ...NFA_ABI,
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "pauseAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "unpauseAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "terminateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "fundAgent",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    name: "withdrawFromAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getState",
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getAgentBalance",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getTokenBoundAccount",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getAgentMetadata",
    outputs: [
      {
        components: [
          { name: "name", type: "string" },
          { name: "persona", type: "string" },
          { name: "voiceHash", type: "bytes32" },
          { name: "animationURI", type: "string" },
          { name: "vaultURI", type: "string" },
          { name: "vaultHash", type: "bytes32" },
          { name: "avatarId", type: "uint8" },
        ],
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const PAYMASTER_ABI = [
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "approveAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "agent", type: "address" }],
    name: "revokeAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "balance",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSponsored",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "approvedAgents",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const BATCH_VERIFIER_ABI = [
  {
    inputs: [
      { name: "proofs", type: "bytes[]" },
      { name: "instances", type: "uint256[][]" },
    ],
    name: "verifyBatch",
    outputs: [{ type: "bool[]" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "proofs", type: "bytes[]" },
      { name: "instances", type: "uint256[][]" },
      { name: "agentIds", type: "uint256[]" },
      { name: "stationIds", type: "uint256[]" },
    ],
    name: "submitBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBatchesProcessed",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalProofsAggregated",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const DEPIN_ORACLE_ABI = [
  {
    inputs: [{ name: "stationId", type: "uint256" }],
    name: "getLatestData",
    outputs: [
      {
        components: [
          { name: "stationId", type: "uint256" },
          { name: "temperature", type: "int256" },
          { name: "humidity", type: "uint256" },
          { name: "windSpeed", type: "uint256" },
          { name: "rainfall", type: "uint256" },
          { name: "timestamp", type: "uint256" },
          { name: "dataHash", type: "bytes32" },
          { name: "signatureVerified", type: "bool" },
          { name: "recoveredSigner", type: "address" },
        ],
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "stationId", type: "uint256" },
      { name: "temperature", type: "int256" },
      { name: "humidity", type: "uint256" },
      { name: "windSpeed", type: "uint256" },
      { name: "rainfall", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    name: "submitWeatherData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "stationId", type: "uint256" }],
    name: "isDataAuthentic",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "stationId", type: "uint256" },
      { name: "stationAddress", type: "address" },
    ],
    name: "registerStation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getStationCount",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
